# Form implementation generated from reading ui file '/home/mark/projects/python/WN2A_RFPeakSearch/ui/direct_programming.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(396, 316)
        Dialog.setSizeGripEnabled(True)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 250, 351, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.direct_btn_sweep = QtWidgets.QPushButton(self.layoutWidget)
        self.direct_btn_sweep.setObjectName("direct_btn_sweep")
        self.hboxlayout.addWidget(self.direct_btn_sweep)
        self.direct_btn_step = QtWidgets.QPushButton(self.layoutWidget)
        self.direct_btn_step.setObjectName("direct_btn_step")
        self.hboxlayout.addWidget(self.direct_btn_step)
        self.direct_btn_cancel = QtWidgets.QPushButton(self.layoutWidget)
        self.direct_btn_cancel.setObjectName("direct_btn_cancel")
        self.hboxlayout.addWidget(self.direct_btn_cancel)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 50, 330, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.direct_stop_freq_mhz = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.direct_stop_freq_mhz.setSuffix("")
        self.direct_stop_freq_mhz.setDecimals(3)
        self.direct_stop_freq_mhz.setMinimum(1.0)
        self.direct_stop_freq_mhz.setMaximum(3000.0)
        self.direct_stop_freq_mhz.setSingleStep(0.001)
        self.direct_stop_freq_mhz.setStepType(QtWidgets.QAbstractSpinBox.StepType.AdaptiveDecimalStepType)
        self.direct_stop_freq_mhz.setProperty("value", 100.0)
        self.direct_stop_freq_mhz.setObjectName("direct_stop_freq_mhz")
        self.gridLayout.addWidget(self.direct_stop_freq_mhz, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.direct_step_freq_mhz = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.direct_step_freq_mhz.setDecimals(3)
        self.direct_step_freq_mhz.setMinimum(0.001)
        self.direct_step_freq_mhz.setSingleStep(0.001)
        self.direct_step_freq_mhz.setProperty("value", 0.001)
        self.direct_step_freq_mhz.setObjectName("direct_step_freq_mhz")
        self.gridLayout.addWidget(self.direct_step_freq_mhz, 2, 1, 1, 1)
        self.direct_start_freq_mhz = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.direct_start_freq_mhz.setDecimals(3)
        self.direct_start_freq_mhz.setMaximum(2999.0)
        self.direct_start_freq_mhz.setSingleStep(0.001)
        self.direct_start_freq_mhz.setStepType(QtWidgets.QAbstractSpinBox.StepType.AdaptiveDecimalStepType)
        self.direct_start_freq_mhz.setProperty("value", 0.0)
        self.direct_start_freq_mhz.setObjectName("direct_start_freq_mhz")
        self.gridLayout.addWidget(self.direct_start_freq_mhz, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.direct_btn_cancel.clicked.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.direct_btn_sweep.setText(_translate("Dialog", "Sweep"))
        self.direct_btn_step.setText(_translate("Dialog", "Step"))
        self.direct_btn_cancel.setText(_translate("Dialog", "&Cancel"))
        self.label_6.setText(_translate("Dialog", "MHz"))
        self.label_3.setText(_translate("Dialog", "Step Freq"))
        self.label_5.setText(_translate("Dialog", "MHz"))
        self.label_2.setText(_translate("Dialog", "Start Freq"))
        self.label_4.setText(_translate("Dialog", "MHz"))
        self.label.setText(_translate("Dialog", "Stop Freq"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
